line.bot:
  channel-token: 'Put Your Channel Token Here.'
  channel-secret: 'Put Your Channel Token Here.'
  handler.path: /callback
  
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://isilo.db.elephantsql.com:5432/ucwqrjit
  username: ucwqrjit
  password: 9yUURpn67-P5gQGkGEIzQlYpa1x8ta8m
