line.bot:
  channel-token: 'Put Your Channel Token Here.'
  channel-secret: 'Put Your Channel Token Here.'
  handler.path: /callback
  
spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://13.250.129.164:27388/portman
  username: app-east
  password: app-east^1999
