line.bot:
  channel-token: '5EWERPnpk8FCBm4d6XIfAhGddKotv2c1YciDKg2W0hCGxWBIVZl2Ufh4lm+zZ/cQGVrJ3hs6qYdFdXUd2kG6vrJ1tDYNsD7bUgZcY80nlThda7u3NMiCXiaRPGHmXpFeSDTyVXxYEK4T6YCTfyTAKAdB04t89/1O/w1cDnyilFU='
  channel-secret: '6ef2ef0a4795dbd4123f628e790ec04d'
  handler.path: /callback
